### ISSUE TITLE
Default samples

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#64] opened 2018-10-03 22:22 UTC
I think ideally we should not need to specify samples, but extract them from conversion table using PatientID...

**Comment by HenrikBengtsson** [comment] 2018-10-03 22:30
Duplicate of Issue #56, or different?

**Comment by ivan108** [comment] 2018-10-03 22:34
Oops, duplicate :)

**Closed** 2018-10-03 22:34 UTC
