### ISSUE TITLE
Error towards end of TRIM on batch run

### ISSUE THREAD

**Issue by shuntsman-ucsf** [UCSF-Costello-Lab/LG3_Pipeline#78] opened 2018-10-10 21:13 UTC
My _trim runs apparently didn't complete successfully as thought. There seems to be an error happening towards the end of trim_galore where it should change the names of the contents of each "trim" directory (from "*.val_1.fq.gz" to "*.fastq.gz" and "*.fastq.gz_trimming_report.txt" to "*QTY_R1.trimming_report.txt").

An example of my trim directory contains the following contents:

> SC300074_AATCCGTC_L007_R2_001_HQ_paired.fastq.gz_trimming_report.txt
> SC300074_AATCCGTC_L007_R2_001_HQ_paired_val_2.fq.gz
> SC300074_AATCCGTC_L007_R1_001_HQ_paired_val_1.fq.gz
> SC300074_AATCCGTC_L007_R1_001_HQ_paired.fastq.gz_trimming_report.txt

End of .err file:

```
RUN STATISTICS FOR INPUT FILE: /zivlab/data2/NP0450-HE9_10_fastq/SC299835_AACAACCA_L001_R2_001_HQ_paired.fastq.gz
 =============================================
 24849941 sequences processed in total
 The length threshold of paired-end sequences gets evaluated later on (in the validation step)
 
 Validate paired-end files SC299835_AACAACCA_L001_R1_001_HQ_paired_trimmed.fq.gz and SC299835_AACAACCA_L001_R2_001_HQ_paired_trimmed.fq.gz
 file_1: SC299835_AACAACCA_L001_R1_001_HQ_paired_trimmed.fq.gz, file_2: SC299835_AACAACCA_L001_R2_001_HQ_paired_trimmed.fq.gz

>>>>> Now validing the length of the 2 paired-end infiles: SC299835_AACAACCA_L001_R1_001_HQ_paired_trimmed.fq.gz and SC299835_AACAACCA_L001_R2_001_HQ_paired_trimmed.fq.gz <<<<<
 Writing validated paired-end read 1 reads to SC299835_AACAACCA_L001_R1_001_HQ_paired_val_1.fq.gz
 Writing validated paired-end read 2 reads to SC299835_AACAACCA_L001_R2_001_HQ_paired_val_2.fq.gz
 
 Total number of sequences analysed: 24849941
 
 Number of sequence pairs removed because at least one read was shorter than the length cutoff (20 bp): 453 (0.00%)
 
 Deleting both intermediate output files SC299835_AACAACCA_L001_R1_001_HQ_paired_trimmed.fq.gz and SC299835_AACAACCA_L001_R2_001_HQ_paired_trimmed.fq.gz
 
====================================================================================================
 
 
 gzip: stdout: Broken pipe
 
 real	74m28.547s
 user	142m51.956s
 sys	1m30.402s
 mv: cannot stat SC299835_AACAACCA_L001_R1_val_1.fq.gz': No such file or directory
 mv: cannot stat SC299835_AACAACCA_L001_R2_val_2.fq.gz': No such file or directory
 mv: cannot stat SC299835_AACAACCA_L001_R1.fastq.gz_trimming_report.txt': No such file or directory
 mv: cannot stat SC299835_AACAACCA_L001_R2.fastq.gz_trimming_report.txt': No such file or directory
```

Full .out file:
```
[2018-10-06 02:12:16 PDT] BEGIN: /var/spool/torque/mom_priv/jobs/1223930.cclc01.som.ucsf.edu.SC
Call: /var/spool/torque/mom_priv/jobs/1223930.cclc01.som.ucsf.edu.SC
Script: /var/spool/torque/mom_priv/jobs/1223930.cclc01.som.ucsf.edu.SC
Arguments: 
Input:
- FASTQ1=/zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R1_001_HQ_paired.fastq.gz
- FASTQ2=/zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R2_001_HQ_paired.fastq.gz
- PROJECT=LG3
- PREFIX=SC299837_CCGAAGTA_L001
- QTY=20
- TG=
Settings:
- LG3_HOME=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28
- LG3_OUTPUT_ROOT=/zivlab/data2/tumorNormal
- EMAIL=scott.huntsman@ucsf.edu
- LG3_SCRATCH_ROOT=/scratch/shuntsman/1223930.cclc01.som.ucsf.edu
- PWD=/home/shuntsman/gh/lg3-test
- USER=shuntsman
- PBS_NUM_PPN=1
FASTQ1=/zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R1_001_HQ_paired.fastq.gz (expanded)
FASTQ2=/zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R2_001_HQ_paired.fastq.gz (expanded)
Started trim_galore on 2018-10-06 02:12:16
Using node(s): n0 
WDIR=/scratch/shuntsman/1223930.cclc01.som.ucsf.edu/SC299837_CCGAAGTA_L001-trim
Current working directory: /scratch/shuntsman/1223930.cclc01.som.ucsf.edu/SC299837_CCGAAGTA_L001-trim
[2018-10-06 02:12:44 PDT] BEGIN: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28/scripts/trim_galore.sh
Call: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28/scripts/trim_galore.sh
Script: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28/scripts/trim_galore.sh
Arguments: -quality=20 /zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R1_001_HQ_paired.fastq.gz /zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R2_001_HQ_paired.fastq.gz
Settings:
- LG3_HOME=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28
- LG3_OUTPUT_ROOT=/zivlab/data2/tumorNormal
- LG3_SCRATCH_ROOT=/scratch/shuntsman/1223930.cclc01.som.ucsf.edu
- PWD=/scratch/shuntsman/1223930.cclc01.som.ucsf.edu/SC299837_CCGAAGTA_L001-trim
- USER=shuntsman
- PBS_NUM_PPN=1
- TG=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28/tools/TrimGalore-0.4.4/trim_galore
- CUTADAPT=/opt/Python/Python-2.7.3/bin/cutadapt
Input:
FQ1=/zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R1_001_HQ_paired.fastq.gz
FQ2=/zivlab/data2/NP0450-HE9_10_fastq/SC299837_CCGAAGTA_L001_R2_001_HQ_paired.fastq.gz
LEN=20
QTY=20
STRINGENCY=1 (ignored; always STRINGENCY=1)
Software:
- TG=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28/tools/TrimGalore-0.4.4/trim_galore
- CUTADAPT=/opt/Python/Python-2.7.3/bin/cutadapt
1.2.1
[2018-10-06 03:26:45 PDT] END: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-09-28/scripts/trim_galore.sh
Current working directory: /home/shuntsman/gh/lg3-test
Removing directory (recursively): /scratch/shuntsman/1223930.cclc01.som.ucsf.edu/SC299837_CCGAAGTA_L001-trim
total 4193224
      4 SC299837_CCGAAGTA_L001_R1_001_HQ_paired.fastq.gz_trimming_report.txt
2096128 SC299837_CCGAAGTA_L001_R1_001_HQ_paired_val_1.fq.gz
      4 SC299837_CCGAAGTA_L001_R2_001_HQ_paired.fastq.gz_trimming_report.txt
2097088 SC299837_CCGAAGTA_L001_R2_001_HQ_paired_val_2.fq.gz
End of PBS script!
Sat Oct  6 03:27:16 PDT 2018
[2018-10-06 03:27:16 PDT] END: /var/spool/torque/mom_priv/jobs/1223930.cclc01.som.ucsf.edu.SC
```

Could it be an issue with running out of /scratch space or other disorientation of working directory?  I noticed all jobs running on n10 died early and assumed some resource issue, but just resubmitted them later and went to different nodes. I submitted ~450 jobs and don't think /scratch is protected for space prior to running (or is it)? 

note: every file is like this. don't be concerned that snippets were taken from different samples' file .err and .out

**Comment by HenrikBengtsson** [comment] 2018-10-10 21:47
Could you please fix the Markdown format to make it a bit easier to read; try to make sure to use code blocks as explained https://guides.github.com/features/mastering-markdown/ - it really improved the readability.

**Comment by ivan108** [comment] 2018-10-10 23:12
It could be that the pipeline expects a certain format for the fastq filenames:
```
${SAMPLE}_R1.fastq.gz
${SAMPLE}_R2.fastq.gz
```
What is your SAMPLE value for the example you gave?
Try renaming your fastq files, e.g. by creating symbolic links with the expected format.

**Comment by shuntsman-ucsf** [comment] 2018-10-10 23:38
Sample for all are of the format SC300074_AATCCGTC_L007
The suffix within the _run_Trim script had to be changed to the format _R2_001_HQ_paired.fastq.gz
I have updated the .out snipped above to include full .out contents.

I also just noticed that the 10-08 version of the _run_Trim included some changes including defaulting $LG3_OUTPUT_ROOT=output whereas 9-28 version did not and relied on external declaration to output.    
Although it seemed to write to the expected output directory for everything else except the mv step, I am rerunning a single sample now using a modified version of the 10-08 _run_Trim.

**Comment by HenrikBengtsson** [comment] 2018-10-10 23:45
> I also just noticed that the 10-08 version of the _run_Trim included some changes including defaulting `LG3_OUTPUT_ROOT=output` whereas 9-28 version did not and relied on external declaration to output.

Yes, this is intended and confirmed to work.  **Make sure you're _not_ setting `LG3_OUTPUT_ROOT` anywhere**.  We are going to deprecate the usage next and eventually get rid of it (by hardcoding it to `output` in the working directory). See Issue #74.

**Comment by ivan108** [comment] 2018-10-11 00:08
Don't use _ (underscores) in the sample IDs, that would save some troubles..

**Comment by HenrikBengtsson** [comment] 2018-10-11 00:39
> Don't use _ (underscores) in the sample IDs, that would save some troubles..

Yes, that could certainly be the reason here.  We should try to set up a small test to see if this is the problem, and if so, we should add code that detects this and gives an informative error message, e.g.
```
ERROR: FASTQ filenames containing underscores (`_`) other than `_R1` and `_R2` are not supported: SC299837_CCGAAGTA_L001_R1_001_HQ_paired.fastq.gz
```
After that, we could look into adding support for this.

@shuntsman-ucsf, as @ivan108 suggests, using symbolic links might be the quickest and savest solution (not a big fan of renaming existing files), e.g.
```sh
$ ln -s SC299837_CCGAAGTA_L001_R1_001_HQ_paired.fastq.gz SC299837-CCGAAGTA-L001_R1.fastq.gz
```
So that the `SAMPLE` name becomes `SC299837-CCGAAGTA-L001`.

**Comment by shuntsman-ucsf** [comment] 2018-10-11 10:04
The test with original _ names, but using the 10-8 version of _run_Trim completed, and it failed the same way.

I then created the links for the same files using no underscores, and re-ran, and it also failed the same way, but created files with the original  names in the _trim directory:
```
SC299997_ATGCCTAA_L003_R2_001_HQ_paired.fastq.gz_trimming_report.txt
SC299997_ATGCCTAA_L003_R2_001_HQ_paired_val_2.fq.gz
...
```
It seems the internal functions were still calling the original _underscored sample names until creating those intermediate output files, but at the end of the .err files, it was looking for the non_underscored files based off the links.
```
mv: cannot stat `SC299997-ATGCCTAA-L004_R1_val_1.fq.gz': No such file or directory
mv: cannot stat `SC299997-ATGCCTAA-L004_R2_val_2.fq.gz': No such file or directory
mv: cannot stat `SC299997-ATGCCTAA-L004_R1.fastq.gz_trimming_report.txt': No such file or directory
mv: cannot stat `SC299997-ATGCCTAA-L004_R2.fastq.gz_trimming_report.txt': No such file or directory
```

I am going to retry the linked names run, but remove the "readlink" calls that are in the _run_Trim script. However that may be thwarted by your intended use of "rawdata", which may require $LG3_INPUT_ROOT to be "readlinked" separately, earlier on.

```
   FASTQ1=${LG3_INPUT_ROOT}/${PREFIX}_R1.fastq.gz
   FASTQ2=${LG3_INPUT_ROOT}/${PREFIX}_R2.fastq.gz

   ## Requires absolute path
  # FASTQ1=$(readlink -e "$FASTQ1")
  # FASTQ2=$(readlink -e "$FASTQ2")
```

**Comment by HenrikBengtsson** [comment] 2018-10-11 14:44
Thanks for the detailed troubleshooting. I agree with you - it's most likely the `readlink -e` that prevents the rename-via-symbolic-link workaround to work.

This morning, I will start setting up simple tests with teeny files to allow us to properly identify and fix this issue.

**Comment by HenrikBengtsson** [comment] 2018-10-11 17:07
Quick update: I'm making progress on supporting underscores (and *_R1/R2* suffixes), cf. Issue #79.  I'm running tests and I think it'll work.

@shuntsman-ucsf, what are your PATIENT names?  Do they also contain underscores?  If not, then it might be that everything else will just work.  If you have, I should add that also in the tests to avoid you running into funny things later.

**Comment by shuntsman-ucsf** [comment] 2018-10-11 18:08
I haven't made the patient_conversion file yet.  I assume it is not needed for trim and align.  But none of my patient IDs have underscores, and I assume I can easily change any value other than the filenames in the tsv if needed.

I will make a separate issue requesting more description of the required values in that file.

**Comment by ivan108** [comment] 2018-10-11 19:11
Yes, older version of the pipeline did not use conversion table for early stages.
But since we have to use it later, why not start using it for all stages.
E.g. it gives the convenience of trimming and aligning only samples for priority patient, without figuring out what are those samples. Or quickly check the patient status, which steps/samples are already done...

**Comment by shuntsman-ucsf** [comment] 2018-10-11 19:44
Just to report that my test where I removed the "readlink" statement did not change anything.

I then readlinked only the $LG3_INPUT_ROOT prior to concatenating to the file name, as below:
```
for PREFIX in ${SAMPLES}
do
   LG3_INPUT_ROOT=$(readlink -e "$LG3_INPUT_ROOT")
   FASTQ1=${LG3_INPUT_ROOT}/${PREFIX}_R1.fastq.gz
   FASTQ2=${LG3_INPUT_ROOT}/${PREFIX}_R2.fastq.gz

   ## Requires absolute path
  # FASTQ1=$(readlink -e "$FASTQ1")
  # FASTQ2=$(readlink -e "$FASTQ2")
```

And that still had the same error.  There is an additional readlink of fastq1 and 2 in trim_galore.pbs that I think will also need to be changed, if that is not already what you are doing.

**Comment by HenrikBengtsson** [comment] 2018-10-11 19:55
Thanks for reporting back.  Yes, there are other places with `readlink` and trying to "hack it" with symbolic links, working around code etc would just paint ourselves into a(nother) corner.  I'm pretty sure i've got a proper fix (only local this far) without hacks.  I'm estimating another 3-5 hours before the tests complete.  

@ivan108, when everything has been validated, I propose that we do another release of what we've got (instead of pointing Scott to the develop version).  I think this will be a good new milestone.

**Comment by ivan108** [comment] 2018-10-11 20:39
Sure, go ahead with another release, I also fixed some bugs and refactored code related to Recal_pass2....

**Comment by HenrikBengtsson** [comment] 2018-10-11 23:16
Ok, I've released LG3_Pipeline 2018-10-11;
```sh
$ module load CBC lg3
$ lg3 --version
2018-10-11
```

@shuntsman-ucsf, please retry with this version.

PS. I've completed the tests for trimming, BWA alignment, and recalibration. I'll keep running the remaining tests later tonight (Issue #79) but since I'll have to head out and it looks all good to me already now, I decided to release already now so you/Scott can launch trimming over night.

**Comment by HenrikBengtsson** [comment] 2018-10-11 23:28
Ha... Murphy's Law.  10 mins after I released, the pindel test failed because some part does not support underscores in the patient name (Issue #81).  Anyway, that doesn't affect @shuntsman-ucsf's needs and especially not his immediate ones.  In other words, go ahead and use LG3_Pipeline 2018-10-11 for now.

**Comment by shuntsman-ucsf** [comment] 2018-10-11 23:59
looking at _run_Trim.... so now it requires patient_conversions file to run? I pre-populated $SAMPLES and it told me it was empty.

**Comment by ivan108** [comment] 2018-10-12 00:50
If you set $SAMPLES, then you don't need $PATIENT and $CONV.
$PATIENT and $CONV are only used to select SAMPLES when they are not already set..

**Comment by HenrikBengtsson** [comment] 2018-10-12 17:52
@shuntsman-ucsf, I see you've got plenty of trimming jobs running on the cluster;  I assume @ivan108's answer helped, correct? I'll be away from my computer most of the day so I won't be able to pitch in, but I think the trimming, the alignment, and recalibration will keep you busy for a while.

**Comment by shuntsman-ucsf** [comment] 2018-10-14 05:33
All 488 _trim jobs seem to have completed successfully.  I submitted the _align jobs Friday, but it seems they are proceeding at a rate of about 60 per 24 hours using only n0 and n31.  Each job is requesting 100GB RAM from the scheduler but I don't see usage of more than 6GB on the adm email and whenever I peak in via top.  Should we reduce the resource request to get more running at a time?

**Comment by ivan108** [comment] 2018-10-14 17:40
We could drop memory request to 64GB, reducing further won't do much, if we want to use 10 cores per job, and typical node has no more than 64 cores, so we can't accommodate more than 6 jobs, no matter how little memory we request...

**Comment by HenrikBengtsson** [comment] 2018-10-14 20:56
Moved the "new feature request" to Issue #82.

It sounds that this issue has been resolved, so I'm closing.  PS. Please try to keep on topic as far as it makes sense and don't start new topics in the same issue thread.  We want to be able to keep issues to a minimal mental unit so that we can easily identify the problem at hand and close quickly.  It will also make it easy to point to previously resolved issues/discussions.

**Closed by HenrikBengtsson** 2018-10-14 20:56 UTC
Labels: bug, high priority
